### ISSUE TITLE
[FEAT] 문제 및 학생 데이터 수집

### ISSUE THREAD

**Issue by Sunwoo0110** [Sunwoo0110/Cheppy-RS#1]
## Description
- CodeChef, CodeForces 사이트에서 데이터 수집

## Todo
- [x] CodeChef: testcase error 해결
- [x] CodeFores: Contest list 수집 추가
- [x] CodeChef: difficulty 추가
- [x] CodeForces: difficulty, point, solved count 추가 (크롤링 -> api 로 변경)
- [x] contest/project csv 파일로 저장 (save 업데이트 방법으로 변경)
- [x] problem csv 파일로 저장
- [ ] code csv 파일로 저장
- [ ] username list, user info 추가
- [ ] username, user csv 파일로 저장
- [ ] 리팩토링
